POST http://localhost:5001/user/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjcxMTQzNzFiMmU4NmY4MGM1YzYxNThmNDUzYzk0NTEyNmZlNzM5Y2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYm9hc3QtYXBwLWF1dGgiLCJhdWQiOiJib2FzdC1hcHAtYXV0aCIsImF1dGhfdGltZSI6MTY0MDQ4NzM4MCwidXNlcl9pZCI6IkdaYmQwd0pXb1hNaEp3TjVQNnFVT1RRTHRwSjIiLCJzdWIiOiJHWmJkMHdKV29YTWhKd041UDZxVU9UUUx0cEoyIiwiaWF0IjoxNjQwNTE4NzYwLCJleHAiOjE2NDA1MjIzNjAsImVtYWlsIjoiY29zbWljcmFyZTdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNvc21pY3JhcmU3QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Fu_vrADdCuG1xjBP6qBHumm7ZxGHjysLVTpX7j-J9NJBNCagOySvdtzKBwoHV1_D0pcjt5gAiBwLx-cxluEreS90VrTlv8ci1ThR20PlErykb_tKlLAdAzMLex5btJq_-C1vaUckuotqV2Y19F1csi3uS6j-KUy239ry6O5Pv2Xs0iWQm72eef4Ptee89nUVTf7wDxl8jsBEvH0M6N_272sz6KcJ6r2OAXgc512XgO8CaFJ5ipOcg2vVeGPo0WHnXfwj7qoMo5AVN4pKaYY4I6xWbGHJBsnoO-bXr6jEi92O8dtHfPjrFQes8r8FXaQ8_gNC-P1ydxX7rmsoLBNuEg"
}

###
POST http://localhost:5001/user/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjcxMTQzNzFiMmU4NmY4MGM1YzYxNThmNDUzYzk0NTEyNmZlNzM5Y2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYm9hc3QtYXBwLWF1dGgiLCJhdWQiOiJib2FzdC1hcHAtYXV0aCIsImF1dGhfdGltZSI6MTY0MDUxODgzNSwidXNlcl9pZCI6ImNqT3ZrOEVIUkxYTmFNank4bXNNMDlVYmY3cDIiLCJzdWIiOiJjak92azhFSFJMWE5hTWp5OG1zTTA5VWJmN3AyIiwiaWF0IjoxNjQwNTY4NjA4LCJleHAiOjE2NDA1NzIyMDgsImVtYWlsIjoieXNvbGFrZXkxMTE2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ5c29sYWtleTExMTZAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.WPU9X1yX9gvNsZO1B77H6kc2EvDr6Eb_OqJITPP0-IOeuaY_xehDTuBnyMLS6rF6yGIgijHAkxcsx6k6j4LpvHutKta9t7C3zOYkpLd4WKRyQzRiLgGIhQzGjDtAyjWMhH8MDa2qNFGOBfwjuPg2mxm5e_9gQx2mHlK3nzQGowlPrS0bzDce7fnb5F7ffzPF4WF0CNNZ1vSxs7KwE7o-dbtkQGLQ17I-fqbiF8Fcb6lps1_5Y6YJwWu8wzQ_tjsdWuJ1t3FXszlNFk_pIeWxKdXu5z31-cCG3yhbdDm14IMZirtubarpnltwCEQClbisb0uNFws0x1z8U47eB4UcaQ"
}

###
POST http://localhost:5001/user/verify
Content-Type: application/json

{
  "token": "adsfasdfasdf"
}

###
POST http://localhost:5001/user
Content-Type: application/json

{
  "email": "ysolakey1116@gmail.com",
  "name": "Tani"
}

###
POST http://localhost:5001/user
Content-Type: application/json

{
  "email": "a",
  "name": ""
}